version: "3.8"
services:
  # PHP Service
  php:
    container_name: main_php
    image: php-fpm-alpine-main3
    # environment:
    #     - APP_ENV=${APP_ENV}
    #     - CONTAINER_ROLE=app
    #     - UID=1000
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ../cms_github/cms:/var/www/cms
    ports:
      - 80:80
    networks:
      - main-prakse-test
      - nginx-proxy
    depends_on:
      - database
      - node

  # Database Server
  database:
    container_name: main_database
    image: mysql:8.0
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - main-prakse-test
  # Node server
  node:
    container_name: main_node_modules
    image: node-alpine-main
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
    tty: true
    ports:
      - 5173:5173
    networks:
      - main-prakse-test

networks:
  main-prakse-test:
    name: main-prakse-test
  nginx-proxy:
    external: true

volumes:
  db-data: ~
