version: "3.8"
services:
    # PHP Service
    php:
        container_name: php
        image: php-fpm-alpine-main-jw
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
            - UID=1000
            - VIRTUAL_HOST=prakse.test
            - VIRTUAL_PORT=9000
            - VIRTUAL_ROOT=/var/www/public
            - VIRTUAL_PROTO=fastcgi
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - prakse-test
        expose:
            - 9000
        depends_on:
            - database
            - nginx-proxy

    # Database Server
    database:
        container_name: database
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - prakse-test
    # Node server
    node:
        container_name: node_modules
        image: node-alpine-main
        volumes:
            - ./:/var/www
            - ./node_modules:/var/www/node_modules
        tty: true
        ports:
            - 5173:5173
        networks:
            - prakse-test

        # Nginx reverse proxy
    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - nginx-certs:/etc/nginx/certs
        networks:
            - prakse-test

networks:
    prakse-test:
        external: true
        name: prakse-test

volumes:
    db-data: ~
    nginx-certs:
