version: "3.9"
services:
  #PHP service
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: php-nginx-cms
    environment:
      APP_ENV: "${APP_ENV}"
      APP_URL: http://${COMPOSE_PROJECT_NAME}.prakse.localhost
      SUBDOMAIN: ${COMPOSE_PROJECT_NAME}
    working_dir: /var/www/html
    volumes:
      - ./cms/${COMPOSE_PROJECT_NAME}:/var/www/html
    networks:
      - prakse-test
      - nginx-proxy

  #Database server
  cms_database:
    container_name: ${COMPOSE_PROJECT_NAME}_database
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - prakse-test

  # # Node server
  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node
    image: node-alpine-cms
    environment:
      APP_URL: http://${COMPOSE_PROJECT_NAME}.prakse.localhost
      ASSET_URL: http://${COMPOSE_PROJECT_NAME}.prakse.localhost
    volumes:
      - ./cms/${COMPOSE_PROJECT_NAME}:/var/www/html
      - node_modules:/var/www/html/node_modules
    tty: true
    networks:
      - prakse-test
    depends_on:
      - php

networks:
  prakse-test:
    name: ${COMPOSE_PROJECT_NAME}-prakse-test
  nginx-proxy:
    external: true

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data
  # user_data:
  #   name: ${COMPOSE_PROJECT_NAME}_user_data
  node_modules:
    name: node_modules_cms

  # node_modules:
  #   name: node_modules_cms
#

# # Nginx server
# nginx:
#   image: nginx_saved
#   container_name: ${COMPOSE_PROJECT_NAME}_nginx
#   environment:
#     - SUBDOMAIN=${COMPOSE_PROJECT_NAME}
#   volumes:
#     - user_data:/var/www/html
#     # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#   ports:
#     - "80"
#   depends_on:
#     - php
#   networks:
#     - prakse-test
#     - nginx-proxy

